# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://michael-pessoni.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: https://michael-pessoni.github.io/

# Title of the Site
title: Michael Pessoni
# Description of the Site
description: Desenvolvendo soluções para a vida
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Michael, Android, Kotlin, Desenvolvedor
# URL for the Image of custom Favicon
favicon-url: https://i.imgur.com/WmaU1H3.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: pessoni94@gmail.com
facebook_username: /
twitter_username: /
instagram_username: pessoni.dev
linkedin_username: michael-pessoni
github_username:  michael-pessoni
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: michael-pessoni

# Name of the Author
author-name: Michael Pessoni
# URL for the Image of the Author
author-image: https://i.imgur.com/pKFCgRP.png
# 60 Words About the Author
author-about: Sou  um Desenvolvedor Android  Jr apaixonado por encontrar soluções que tornem a vida das pessoas mais fácil.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/michael-pessoni

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
